language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2

env:
  - TYPO3_VERSION=^7.6 COVERAGE=0 FUNCTIONAL=0
  - TYPO3_VERSION=^8.7 COVERAGE=0 FUNCTIONAL=0
  - TYPO3_VERSION=dev-master COVERAGE=0 FUNCTIONAL=0

matrix:
  exclude:
    - env: TYPO3_VERSION=dev-master COVERAGE=0 FUNCTIONAL=0
      php: 5.5
    - env: TYPO3_VERSION=dev-master COVERAGE=0 FUNCTIONAL=0
      php: 5.6
    - env: TYPO3_VERSION=^8.7 COVERAGE=0 FUNCTIONAL=0
      php: 5.5
    - env: TYPO3_VERSION=^8.7 COVERAGE=0 FUNCTIONAL=0
      php: 5.6
  include:
    - env: TYPO3_VERSION=^7.6 COVERAGE=1 FUNCTIONAL=1
      php: 7.1
    - env: TYPO3_VERSION=^8.7 COVERAGE=0 FUNCTIONAL=1
      php: 7.1
    - env: TYPO3_VERSION=dev-master COVERAGE=0 FUNCTIONAL=1
      php: 7.1
  allow_failures:
    - env: TYPO3_VERSION=dev-master COVERAGE=0 FUNCTIONAL=1
    - env: TYPO3_VERSION=dev-master COVERAGE=0 FUNCTIONAL=0
    - php: 7.2

addons:
  apt:
    packages:
      - parallel

before_script:
  - composer self-update
  - export COMPOSER_VENDOR_DIR=".Build/vendor"
  - export COMPOSER_BIN_DIR=".Build/bin"
  - composer config extra.typo3/cms.web-dir ".Build/Web"
  - composer config extra.typo3/cms.cms-package-dir "${COMPOSER_VENDOR_DIR}/typo3/cms"
  - composer require --dev typo3/cms="$TYPO3_VERSION"
  # Restore composer.json
  - git checkout composer.json
  - export TYPO3_PATH_WEB="$(pwd)/.Build/Web"
  # Create extension symlink in typo3conf/ext folder
  - mkdir -p .Build/Web/typo3conf/ext
  - ln -snvf ../../../../. .Build/Web/typo3conf/ext/feature_flag

script:
  - echo "Running unit tests";
  - OPT_COVERAGE=$([[ "$COVERAGE" == "1" ]] && echo "--coverage-clover=ut-coverage.clover" || echo;)
  - .Build/bin/phpunit -c Tests/phpunit.xml $OPT_COVERAGE

  - echo "Running functional tests";
  - OPT_COVERAGE=$([[ "$COVERAGE" == "1" ]] && echo "--coverage-clover=ft-{}-coverage.clover" || echo;)
  - >
    export typo3DatabaseName="typo3";
    export typo3DatabaseHost="localhost";
    export typo3DatabaseUsername="root";
    export typo3DatabasePassword="";

    find 'Tests/Functional' -wholename '*Test.php' -o -name '*Test.php' | parallel --gnu 'echo "Running functional test suite {}"; .Build/bin/phpunit -c Tests/functional.xml $OPT_COVERAGE --bootstrap .Build/Web/typo3/sysext/core/Build/FunctionalTestsBootstrap.php {}'

  # Upload code coverage data, if enabled
  - >
    if [[ "$COVERAGE" == "1" ]]; then
      echo "Uploading code coverage results";
      wget https://scrutinizer-ci.com/ocular.phar
      find . -wholename '*-coverage.clover' -o -name '*-coverage.clover' | xargs -i php ocular.phar code-coverage:upload --format=php-clover {}
    fi

  - >
    echo "Running php lint";
    find . -name \*.php ! -path "./.Build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;
