language: php

php:
  - 5.5
  - 5.6

env:
  - TYPO3_VERSION=^7.6 COVERAGE=1

addons:
  apt:
    packages:
      - parallel

before_script:
  - composer self-update
  - composer require --dev typo3/cms="$TYPO3_VERSION"
  # Restore composer.json
  - git checkout composer.json

  - export TYPO3_PATH_WEB="$(pwd)/.Build/Web"

script:
  - echo "Running unit tests";
  - OPT_COVERAGE=$([[ $COVERAGE == "1" ]] && echo "--coverage-clover=ut-coverage.clover" || echo;)
  - .Build/bin/phpunit -c Tests/phpunit.xml $OPT_COVERAGE

  - echo "Running functional tests";
  - OPT_COVERAGE=$([[ $COVERAGE == "1" ]] && echo "--coverage-clover=ft-{}-coverage.clover" || echo;)
  - >
    export typo3DatabaseName="typo3";
    export typo3DatabaseHost="localhost";
    export typo3DatabaseUsername="root";
    export typo3DatabasePassword="";

    find 'Tests/Functional' -wholename '*Test.php' -o -name '*Test.php' | parallel --gnu 'echo "Running functional test suite {}"; .Build/bin/phpunit -c Tests/functional.xml $OPT_COVERAGE {}'

  # Upload code coverage data, if enabled
  - >
    if [[ "$COVERAGE" == "1" ]]; then
      echo "Uploading code coverage results";
      wget https://scrutinizer-ci.com/ocular.phar
      find . -wholename '*-coverage.clover' -o -name '*-coverage.clover' | xargs -i php ocular.phar code-coverage:upload --format=php-clover {}
    fi
